### ISSUE TITLE
Site request: jango.com

### ISSUE THREAD

**Issue by benshep** [carlin-q-scott/browser-media-players#22]
I'd like to request a new site please: **jango.com**.

I've looked at the button controls and they look pretty simple. In fact I got as far as I could, adding a `jango.com-view.js` file but I haven't been able to test it. Here's the content of that file:

```
/**
 * MediaKeys namespace.
 */
if (typeof MediaKeys == "undefined") var MediaKeys = {};

MediaKeys.playButton = "//a[@id='btn-playpause']/button[@class='pcb']";
MediaKeys.pauseButton = "//a[@id='btn-playpause']/button[@class='pcb']";
MediaKeys.skipButton = "//a[@id='btn-ff']/button[@class='pcb']";
MediaKeys.previousButton = "//a[@id='btn-rewind']/button[@class='pcb']";
```

**Comment by carlin-q-scott** [comment]
@benshep Would you like to open a PR so I can help you finish your work and get you credit for it? I know testing is a bit wonky right now. Something changed either in Firefox or VSCode that caused it to not totally work.

**Comment by benshep** [comment]
Yep, will do. I wasn't sure if testing was something I could do myself or
whether I'd got something wrong.

**Comment by carlin-q-scott** [comment]
@benshep Oh, you should be able to test it yourself; There's a section in the Readme about it but you may need to add the compiled add-on to Firefox manually rather than use the debugger.

My only comment about your code is that you probably don't need the `[@class='pcb']` pieces since there probably aren't multiple buttons inside of the anchor/link elements. Simple is better for the locators/xpaths.

**Comment by benshep** [comment]
Hmm, yes - I read the readme but I didn't know how to compile an add-on myself...

Anyway, here's a PR for you. I took your advice on the XPaths.
