### ISSUE TITLE
Privacy violation in new version

### ISSUE THREAD

**Issue by cup** [carlin-q-scott/browser-media-players#36]
New version requires this

- Access your data for sites in the kanopy.com domain
- Access your data for shop.attackthemusic.com

I am uninstalling this addon for now, please resolve

**Comment by carlin-q-scott** [comment]
@cup That's how this addon adds support for those sites. It already had access to over two dozen sites. Most add-ons just ask for access to all site data to avoid updates asking for additional permissions. I prefer notifying people when new sites are added.

**Comment by carlin-q-scott** [comment]
It may make you feel comfortable if you knew where these permissions are requested in the source code. Every ["matches" entry in the extension manifest.json](https://github.com/carlin-q-scott/browser-media-players/blob/master/manifest.json#L66) defines a domain that the extension works with and needs access to.

**Comment by cup** [comment]
@carlin-q-scott thank you

However this information should be documented, else people dont know what they are agreeing to. A search for `kanopy` in this repo only yield this:

https://github.com/carlin-q-scott/browser-media-players/blob/635561cfd94f50b8c030d69b8dad7eae42293a61/manifest.json#L287-L295

and a search for `access` pretty much returns nothing:

https://github.com/carlin-q-scott/browser-media-players/search?q=access

**Comment by Instagit** [comment]
This is the exact opposite of a privacy violation. The addon only asks permissions for sites that are actually required, unlike most addons that ask for access to all your sites.

Instead of uninstalling and complaining, you should be thanking the author.

**Comment by carlin-q-scott** [comment]
It's ok, people who don't have a lot of browser extensions have a right to be confused and concerned about an extension asking to view sites they have never visited.

I have looked into providing a toggle button to enable a supported site, rather than requesting permission to every site that's supported. It's complicated but doable.

@cup Sadly Firefox documentation doesn't explicitly state that the "matches" key results in a permissions request, but it does. This is the closest they get to stating that: 
>Host permissions are specified as match patterns, and each pattern identifies a group of URLs for which the extension is requesting extra privileges. For example, a host permission could be "*://developer.mozilla.org/*"

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/permissions#Host_permissions
